import os
import gc

import matplotlib
from scipy.sparse import csr_matrix
import pandas as pd
import scanpy as sc
import scvi
import torch
from anndata import AnnData
from dotenv import load_dotenv

# Supports file saving only; GUI rendering is not available
matplotlib.use("Agg")
# **If you are using NVIDIA GPU** this will adjust `float32_matmul_precision` to 'high' (TF32, default 'highest which is FP32), which accelerates matrix multiplication.
torch.set_float32_matmul_precision("high")
# Loading .env
load_dotenv()

base_directory = os.getenv("PROCESSED_COUNT_FILE_LOCATION", ".")
anndata_list : list[AnnData] = []

def sc_rna_seq_preprocessing(csv_gz_path) -> AnnData:
    adata: AnnData = sc.read_csv(csv_gz_path).T
    # Converting to csr_matrix for:
    # 1. Memory efficiency (Not loading numerous zeros in memory)
    # 2. Faster arithmetic and matrix vector operations
    if not isinstance(adata.X, csr_matrix):
        adata.X = csr_matrix(adata.X)
    anndata = adata.copy()

    # =========================================================
    # Removing Doublets
    # =========================================================
    # Keep genes which are expressed in at least 10 cells
    sc.pp.filter_genes(adata, min_cells=10)
    # Select genes with high variance
    # VST (Variance Stabilizing Transformation) algorithm (in this case, seruat_v3) is applied due to high variance in genes with high level of expression
    # Variance Stabilization is needed to select genes with whose variance is higher than expected
    sc.pp.highly_variable_genes(adata, n_top_genes=2000, subset=True, flavor="seurat_v3")

    # Single-Cell Variational Inference (SCVI) separates technical noise (batch effect, library size) from the data
    # By using ZINB (Zero-Inflated Negative Binominal) distribution, zero-inflation (too many zeros, because negative count is impossible) and overdispersion (dispersion greater than mean value, because certain RNAs exhibit minimal basal trnanscription but undergo rapid induction only under specific conditions) can be handled
    # SCVI uses VAE (Variational AutoEncoder) structure, encoder maps data x into latent varaible z and decoder restores data x from latent variable z and technical noises

    # Adds fields to the AnnData objet to make it ready for building a Pytorch neural network
    # By default every cell is considered as a single batch
    scvi.model.SCVI.setup_anndata(adata)
 
    # Constructs a VAE Pytorch neural network, not yet trained (Weights are initialized with random values)
    # Default dimension of SCVI latent space is 10
    vae = scvi.model.SCVI(adata, n_latent=10)
    # Trains a VAE Pytorch neural network
    vae.train()

    # SOLO (Single-cell Doublet Detection via Variational Inference) identifies whether the cell is a singlet or a doublet
    # A decoder of VAE is not required because technical noise has already been accounted for and filtered out with the latent representation produced by the encoder

    # Constructs a SOLO instance by attaching a classifier head to the pretrained VAE encoder
    solo = scvi.external.SOLO.from_scvi_model(vae)
    # SOLO utilizes Positive-Unlabeled (PU) learning, incorporating synthetic doublets generated by summing the counts of two randomly selected cells.
    # This could reveal both heterotypic doublets (e.g. T cell + B cell) and homotypic doublets (e.g. T cell + T cell)
    # Trains a SOLO instance
    solo.train()
    # 'soft' True returns probabilities for singlet and doublet 
    df = solo.predict(soft=True)
    print(df.head())
    # 'soft' False returns binary determination whether the cell is a singlet or a doublet
    df["prediction"] = solo.predict(soft=False)
    # Removes the suffix from the barcode
    df.index = df.index.map(lambda x: x[:-2])

    df["dif"] = df["doublet"] - df["singlet"]
    doublets = df[(df["prediction"] == "doublet") & (df["dif"] > 1)]
    anndata.obs["doublet"] = anndata.obs.index.isin(doublets.index)
    anndata = anndata[~anndata.obs["doublet"]].copy()

    anndata.obs['Sample'] = "_".join(csv_gz_path.split('/')[-1].split('_')[:-2])

    # =========================================================
    # Preprocessing
    # =========================================================
    sc.pp.filter_cells(anndata, min_genes=200)
    # Gene filtering will be done after AnnData integration of multiple samples
    
    # Marking mitochondrial and ribosomal genes
    anndata.var["mt"] = anndata.var.index.str.startswith("MT-")
    # This file is relatively small
    ribo_url = "http://software.broadinstitute.org/gsea/msigdb/download_geneset.jsp?geneSetName=KEGG_RIBOSOME&fileType=txt"
    ribo_genes = pd.read_table(ribo_url, skiprows=2, header=None)
    anndata.var["ribo"] = anndata.var_names.isin(ribo_genes[0].values)

    # Generates QC metrics
    # qc_vars: List of categories that you want to make as a QC metrics (It must be set as a boolean list in AnnData.obs)
    sc.pp.calculate_qc_metrics(
        anndata, qc_vars=["mt", "ribo"], percent_top=None, log1p=False, inplace=True
    )
    # Cytoplasmic RNA in dead cells leaks out, resulting in a higher proportion of remaining mitochondrial RNA
    anndata = anndata[anndata.obs["pct_counts_mt"] < 20]
    
    return anndata

for file in os.listdir(base_directory):
    anndata_list.append(sc_rna_seq_preprocessing(os.path.join(base_directory, file)))

integrated_anndata = sc.concat(anndata_list)
# To save memory
del anndata_list
gc.collect()

# You can read and write the integrated AnnData
# integrated_anndata.write_h5ad("combined.h5ad")
# integrated_anndata = sc.read_h5ad("combined.h5ad")

# Gene filtering after AnnData integration of multiple samples
sc.pp.filter_genes(integrated_anndata, min_cells=100)
assert isinstance(integrated_anndata.X, csr_matrix)
integrated_anndata.layers['counts'] = integrated_anndata.X.copy()

# Normalization and Log Transformation
sc.pp.normalize_total(integrated_anndata, target_sum=1e4)
sc.pp.log1p(integrated_anndata)

# Setting up AnnData for SCVI model with covariates
# In this case, we use AnnData layer "counts" instead of X
# In this case, "Sample", 'pct_counts_mt', 'total_counts', 'pct_counts_ribo' are expected to contribute to the noises
scvi.model.SCVI.setup_anndata(integrated_anndata, 
                              layer = "counts",
                              categorical_covariate_keys=["Sample"],
                              continuous_covariate_keys=['pct_counts_mt', 'total_counts', 'pct_counts_ribo'])
model = scvi.model.SCVI(integrated_anndata)
model.train()

# latent_representation: cell x latent_space_dimension
integrated_anndata.obsm["X_scVI"] = model.get_latent_representation()
# Denoised RNA expression
integrated_anndata.obsm["X_normalized_scVI"] = model.get_normalized_expression(library__size = 1e4)

# Uses pre-calculated SCVI latent representation for calculating similarity score and constructing neighborhood graph
# Store settings in .uns["neighbors"] and connectivity matrices in .obsp
sc.pp.neighbors(integrated_anndata, use_rep = "X_scVI")
# Embeds the neighborhood graph into 2D space using UMAP algorithm (optimized via SGD, Stochastic Gradient Descent)
# You can change n_components to 3 for 3D UMAP
sc.tl.umap(integrated_anndata, n_components=2)
# Clustering cells using leiden algorithm, maximizes modularity which is defined based on its intergroup connectivity and expected (random) connectivity
# High resolution value results in more clusters
sc.tl.leiden(integrated_anndata, resolution=0.5, flavor="igraph", n_iterations=2, directed=False)
# Visualizes UMAP with leiden clusters and samples (Rendering a graph each)
# String "umap" is added to the filename automatically
sc.pl.umap(integrated_anndata, color=["leiden", "Sample"], projection = '2d',frameon = False, save = "_leiden_sample.png")

