# %%
import os
import gc

import matplotlib
# Supports file saving only; GUI rendering is not available
matplotlib.use("Agg")

from anndata import AnnData
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import matplotlib.patheffects as patheffects
from matplotlib.axes import Axes
import numpy as np
import pandas as pd
import scanpy as sc
from scipy.sparse import csr_matrix
import scvi
import seaborn as sns
import torch


# **If you are using NVIDIA GPU** this will adjust `float32_matmul_precision` to 'high' (TF32, default 'highest which is FP32), which accelerates matrix multiplication.
torch.set_float32_matmul_precision("high")

# Loading .env
load_dotenv()
base_directory = os.getenv("PROCESSED_COUNT_FILE_LOCATION", ".")

sns.set_theme(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

# %%
def load_data(csv_gz_path) -> AnnData:
    adata: AnnData = sc.read_csv(csv_gz_path).T
    # Converting to csr_matrix for memory efficiency and speed
    if not isinstance(adata.X, csr_matrix):
        adata.X = csr_matrix(adata.X)
    adata.obs['Sample'] = "_".join(csv_gz_path.split('/')[-1].split('_')[:-2])
    return adata

# Detecting Doublets
def doublet_removal(adata: AnnData) -> AnnData:
    vae_adata = adata.copy()
    # Keep genes which are expressed in at least 10 cells
    sc.pp.filter_genes(vae_adata, min_cells=10)
    # Select genes with high variance
    # VST (Variance Stabilizing Transformation) algorithm (in this case, seruat_v3) is applied due to high variance in genes with high level of expression
    # Variance Stabilization is needed to select genes with whose variance is higher than expected
    sc.pp.highly_variable_genes(vae_adata, n_top_genes=2000, subset=True, flavor="seurat_v3")

    # Single-Cell Variational Inference (SCVI) separates technical noise (batch effect, library size) from the data
    # By using ZINB (Zero-Inflated Negative Binominal) distribution, zero-inflation (too many zeros, because negative count is impossible) and overdispersion (dispersion greater than mean value, because certain RNAs exhibit minimal basal trnanscription but undergo rapid induction only under specific conditions) can be handled
    # SCVI uses VAE (Variational AutoEncoder) structure, encoder maps data x into latent varaible z and decoder restores data x from latent variable z and technical noises

    # Adds fields to the AnnData objet to make it ready for building a Pytorch neural network
    # By default every cell is considered as a single batch
    scvi.model.SCVI.setup_anndata(vae_adata)
 
    # Constructs a VAE Pytorch neural network, not yet trained (Weights are initialized with random values)
    # Default dimension of SCVI latent space is 10
    vae = scvi.model.SCVI(vae_adata, n_latent=10)
    # Trains a VAE Pytorch neural network
    vae.train()

    # SOLO (Single-cell Doublet Detection via Variational Inference) identifies whether the cell is a singlet or a doublet
    # A decoder of VAE is not required because technical noise has already been accounted for and filtered out with the latent representation produced by the encoder

    # Constructs a SOLO instance by attaching a classifier head to the pretrained VAE encoder
    solo = scvi.external.SOLO.from_scvi_model(vae)
    # SOLO utilizes Positive-Unlabeled (PU) learning, incorporating synthetic doublets generated by summing the counts of two randomly selected cells.
    # This could reveal both heterotypic doublets (e.g. T cell + B cell) and homotypic doublets (e.g. T cell + T cell)
    # Trains a SOLO instance
    solo.train()
    # 'soft' True returns probabilities for singlet and doublet 
    solo_probs = solo.predict(soft=True)
    adata.obs['singlet_probability'] = solo_probs['singlet']
    adata.obs['singlet_probability'] = adata.obs['singlet_probability'].fillna(0)
    
    del vae, solo, vae_adata
    gc.collect()

    return adata

def quality_assess(adata: AnnData, ribo_genes: pd.DataFrame) -> AnnData:
    # Marking mitochondrial and ribosomal genes
    adata.var["mt"] = adata.var.index.str.startswith("MT-")
    adata.var["ribo"] = adata.var_names.isin(ribo_genes[0].values)
    # Generates QC metrics
    # qc_vars: List of categories that you want to make as a QC metrics (It must be set as a boolean list in AnnData.obs)
    sc.pp.calculate_qc_metrics(
        adata, qc_vars=["mt", "ribo"], percent_top=[20], log1p=True, inplace=True
    )

    return adata

# %% 
anndata_list : list[AnnData] = []
ribo_url = "http://software.broadinstitute.org/gsea/msigdb/download_geneset.jsp?geneSetName=KEGG_RIBOSOME&fileType=txt"
ribo_genes = pd.read_table(ribo_url, skiprows=2, header=None)

# Preprocessing each sample
for file in os.listdir(base_directory):
    loaded_adata = load_data(os.path.join(base_directory, file))
    doublet_removed_adata = doublet_removal(loaded_adata)
    quality_assessed_adata = quality_assess(doublet_removed_adata, ribo_genes)

    anndata_list.append(quality_assessed_adata)
# %% [markdown]
# ### Visualizes sample quality metrics across multiple samples

# %%
anndata_obj_list: list[pd.DataFrame] = []
for adata in anndata_list:
    assert isinstance(adata.obs, pd.DataFrame)
    anndata_obj_list.append(adata.obs)
sample_quality = pd.concat(anndata_obj_list).sort_values("Sample")

variables = ["singlet_probability", "pct_counts_mt", "n_genes_by_counts", "pct_counts_in_top_20_genes", "log1p_total_counts"]
pretty_names = {
    "singlet_probability": "Singlet Probability",
    "pct_counts_mt": "Mitochondrial Fraction (%)",
    "n_genes_by_counts": "Detected Genes",
    "pct_counts_in_top_20_genes": "Library Complexity (Top 20%)",
    "log1p_total_counts": "Sequencing Depth (Log1p UMI)",
}

qc_ridgeplot_dir = "qc_ridgeplots"
os.makedirs(qc_ridgeplot_dir, exist_ok=True)

for variable in variables:
    # Initializes seaborn FacetGrid
    sns_grid = sns.FacetGrid(
            sample_quality, 
            row="Sample", 
            hue="Sample", 
            aspect=15, 
            height=0.6, 
            palette="tab20",
            sharex = True,
        )
    # Draw KDE (Kernel Density Estimation) plot
    sns_grid.map(sns.kdeplot, variable, clip_on=False, fill=True, alpha=0.8, linewidth=1.5)
    # Outlining the KDE plot with white line
    sns_grid.map(sns.kdeplot, variable, clip_on=False, color="w", linewidth=2)
    # Depicting a y axis
    sns_grid.map(plt.axhline, y=0, linewidth=2, clip_on=False)
    
    # Write sample names on the left side of each KDE plot
    def label(_, color, label):
        kde_plot = plt.gca()
        text = kde_plot.text(1, 0.2, label, fontweight="bold", color=color,
                ha="right", va="center", transform=kde_plot.transAxes)
        text.set_path_effects([
            patheffects.withStroke(linewidth=3, foreground="w")
        ])
    sns_grid.map(label, variable)

    # Allow subplots to overlap
    sns_grid.figure.subplots_adjust(hspace=-0.4)
    # Remove unnecessary subplot details
    sns_grid.set_titles("")
    # Remove y-axis ticks and labels
    sns_grid.set(yticks=[], ylabel="")
    # Remove spines (Outer box of each subplot)
    sns_grid.despine(bottom=True, left=True)

    for kde_plot in sns_grid.axes.flat:
        kde_plot: Axes = kde_plot
        # Draw median line (Red)
        kde_plot.axvline(x=sample_quality[variable].median(), color='r', linestyle='-', alpha=0.5)
        
        # Special logic: Draw threshold line only for Singlet Probability
        if variable == "singlet_probability":
            kde_plot.axvline(x=0.6, color='blue', linestyle='--', linewidth=2)
            kde_plot.text(0.6, 0.5, ' Cutoff (0.6)', color='blue', transform=kde_plot.get_xaxis_transform(), fontsize=8)
        
        # Set X-axis label
        kde_plot.set_xlabel(pretty_names.get(variable, variable))

    filename = os.path.join(qc_ridgeplot_dir, f"{variable}.svg")
    plt.savefig(filename, format='svg', bbox_inches='tight')
    plt.close()

# %%
integrated_anndata = sc.concat(anndata_list)
# To save memory
del anndata_list
gc.collect()

# You can read and write the integrated AnnData
# integrated_anndata.write_h5ad("combined.h5ad")
# integrated_anndata = sc.read_h5ad("combined.h5ad")

# %%
# Cell and gene filtering
sc.pp.filter_cells(integrated_anndata, min_genes=200)
sc.pp.filter_genes(integrated_anndata, min_cells=100)
# Cytoplasmic RNA in dead cells leaks out, resulting in a higher proportion of remaining mitochondrial RNA
integrated_anndata = integrated_anndata[integrated_anndata.obs["pct_counts_mt"] < 20].copy()

# %%
# Setting up AnnData for SCVI model with covariates
# In this case, we use AnnData layer "counts" instead of X
# In this case, "Sample", 'pct_counts_mt', 'total_counts', 'pct_counts_ribo' are expected to contribute to the noises
scvi.model.SCVI.setup_anndata(integrated_anndata, 
                              categorical_covariate_keys=["Sample"],
                              continuous_covariate_keys=['pct_counts_mt', 'total_counts', 'pct_counts_ribo'])
model = scvi.model.SCVI(integrated_anndata)
model.train()

# latent_representation: (cell, latent_space_dimension)
integrated_anndata.obsm["x_scvi"] = model.get_latent_representation()
# Denoised RNA expression
integrated_anndata.obsm["scvi_normalized"] = model.get_normalized_expression(library_size = 1e4)

# Uses pre-calculated SCVI latent representation for calculating similarity score and constructing neighborhood graph
# Store settings in .uns["neighbors"] and connectivity matrices in .obsp
sc.pp.neighbors(integrated_anndata, use_rep = "x_scvi")
# Embeds the neighborhood graph into 2D space using UMAP algorithm (optimized via SGD, Stochastic Gradient Descent)
# You can change n_components to 3 for 3D UMAP
sc.tl.umap(integrated_anndata, n_components=2)
# Clustering cells using leiden algorithm, maximizes modularity which is defined based on its intergroup connectivity and expected (random) connectivity
# High resolution value results in more clusters
sc.tl.leiden(integrated_anndata, resolution=1.0, flavor="igraph", n_iterations=2, directed=False)
# Visualizes UMAP with leiden clusters and samples (Rendering a graph each)
# String "umap" is added to the filename automatically
#%%
shuffled_adata = integrated_anndata[np.random.permutation(integrated_anndata.n_obs)]
_, axs = plt.subplots(1, 2, figsize=(10, 5))

sc.pl.umap(
    shuffled_adata, 
    color="leiden", 
    projection = '2d',
    ax=axs[0],             
    legend_loc="on data",  
    legend_fontoutline=2,  
    frameon=False,         
    title="Leiden Clustering", 
    show=False             
)
sc.pl.umap(
    shuffled_adata, 
    color="Sample", 
    projection = '2d',
    ax=axs[1],      
    frameon=False,
    title="Sample Distribution",
    show=False
)

plt.tight_layout()
plt.savefig("umap_leiden_sample.svg", bbox_inches='tight', format='svg')
plt.close()