# %% Environment Setup
import gc
import os
import numpy as np
import pandas as pd
import scanpy as sc
import scvi
from anndata import AnnData
from pipeline.utils import plot
from pipeline.utils.env import find_env_dir
from pipeline.config.constants import (
    DOUBLET_REMOVAL_VAE_BATCH_SIZE,
    DOUBLET_REMOVAL_SOLO_BATCH_SIZE,
    SINGLE_CELL_VAE_BATCH_SIZE,
)
from pipeline.config.machine_learning import DataLoader

# Loading .env
h5ad_count_matrix_location = find_env_dir("H5AD_COUNT_MATRIX_LOCATION")
file_name = "SCP1038.h5ad"
file = os.path.join(h5ad_count_matrix_location, file_name)


# %%  Preprocessing functions
# Detecting and annotating doublets using SCVI and SOLO
def doublet_removal(adata: AnnData) -> AnnData:
    # Select genes which are expressed in at least 10 cells
    filtered_genes_candidate = sc.pp.filter_genes(adata, min_cells=10, inplace=False)
    if filtered_genes_candidate is None:
        raise ValueError("No gene left after filtering")
    filtered_genes, _ = filtered_genes_candidate

    # Select genes with high variance
    # VST (Variance Stabilizing Transformation) algorithm (in this case, seruat_v3) is applied due to high variance in genes with high level of expression
    # Variance Stabilization is needed to select genes with whose variance is higher than expected
    adata_gene_view = adata[:, filtered_genes]
    highly_variable_genes_candidate = sc.pp.highly_variable_genes(
        adata_gene_view,
        n_top_genes=2000,
        subset=False,
        flavor="seurat_v3",
        inplace=False,
    )
    if highly_variable_genes_candidate is None:
        raise ValueError("Failed to compute highly variable genes")
    highly_variable_genes = highly_variable_genes_candidate

    vae_adata = adata_gene_view[
        :, highly_variable_genes["highly_variable"].to_numpy()
    ].copy()

    # Single-Cell Variational Inference (SCVI) separates technical noise (batch effect, library size) from the data
    # By using ZINB (Zero-Inflated Negative Binominal) distribution, zero-inflation (too many zeros, because negative count is impossible) and overdispersion (dispersion greater than mean value, because certain RNAs exhibit minimal basal trnanscription but undergo rapid induction only under specific conditions) can be handled
    # SCVI uses VAE (Variational AutoEncoder) structure, encoder maps data x into latent varaible z and decoder restores data x from latent variable z and technical noises

    # Adds fields to the AnnData objet to make it ready for building a Pytorch neural network
    # By default every cell is considered as a single batch
    scvi.model.SCVI.setup_anndata(vae_adata)

    # Constructs a VAE Pytorch neural network, not yet trained (Weights are initialized with random values)
    # Default dimension of SCVI latent space is 10
    vae = scvi.model.SCVI(vae_adata, n_latent=10)
    # Trains a VAE Pytorch neural network
    vae.train(
        accelerator="gpu",
        batch_size=DOUBLET_REMOVAL_VAE_BATCH_SIZE,
        datasplitter_kwargs=DataLoader,
        train_size=0.9,
        check_val_every_n_epoch=1,
    )
    plot.plot_validation_loss(
        vae, vae_adata.obs["series"].iloc[0] + "_validation_loss.svg"
    )

    # SOLO (Single-cell Doublet Detection via Variational Inference) identifies whether the cell is a singlet or a doublet
    # A decoder of VAE is not required because technical noise has already been accounted for and filtered out with the latent representation produced by the encoder

    # Constructs a SOLO instance by attaching a classifier head to the pretrained VAE encoder
    solo = scvi.external.SOLO.from_scvi_model(vae)
    # SOLO utilizes Positive-Unlabeled (PU) learning, incorporating synthetic doublets generated by summing the counts of two randomly selected cells.
    # This could reveal both heterotypic doublets (e.g. T cell + B cell) and homotypic doublets (e.g. T cell + T cell)
    # Trains a SOLO instance
    solo.train(
        accelerator="gpu",
        batch_size=DOUBLET_REMOVAL_SOLO_BATCH_SIZE,
        datasplitter_kwargs=DataLoader,
        train_size=0.9,
        check_val_every_n_epoch=1,
    )
    plot.plot_validation_loss(
        solo, vae_adata.obs["series"].iloc[0] + "_solo_validation_loss.svg"
    )
    # 'soft' True returns probabilities for singlet and doublet
    solo_probs = solo.predict(soft=True)
    adata.obs["singlet_probability"] = solo_probs["singlet"]

    del vae, solo, vae_adata
    gc.collect()

    return adata


# Quality assessment by calculating QC metrics
def quality_assess(adata: AnnData, ribo_genes: pd.DataFrame) -> AnnData:
    # Marking mitochondrial and ribosomal genes
    mt_mask = adata.var.index.str.startswith("MT-")
    ribo_mask = adata.var_names.isin(ribo_genes[0].values)
    adata.var["mt"] = np.asarray(mt_mask, dtype=bool)
    adata.var["ribo"] = np.asarray(ribo_mask, dtype=bool)

    # Generates QC metrics
    # qc_vars: List of categories that you want to make as a QC metrics (It must be set as a boolean list in AnnData.obs)
    sc.pp.calculate_qc_metrics(
        adata, qc_vars=["mt", "ribo"], percent_top=[20], log1p=True, inplace=True
    )

    return adata


# %%
ribo_url = "http://software.broadinstitute.org/gsea/msigdb/download_geneset.jsp?geneSetName=KEGG_RIBOSOME&fileType=txt"
ribo_genes = pd.read_table(ribo_url, skiprows=2, header=None)

# Preprocessing each sample
loaded_adata = sc.read_h5ad(file)
doublet_removed_adata = doublet_removal(loaded_adata)
processed_adata = quality_assess(doublet_removed_adata, ribo_genes)

plot.plot_qc(processed_adata)

# %%

# Cell and gene filtering
sc.pp.filter_cells(processed_adata, min_genes=200)
sc.pp.filter_genes(processed_adata, min_cells=100)
# Cytoplasmic RNA in dead cells leaks out, resulting in a higher proportion of remaining mitochondrial RNA
processed_adata = processed_adata[processed_adata.obs["pct_counts_mt"] < 20].copy()

# %%
# Setting up AnnData for SCVI model with batch effects
# In this case, we use AnnData layer "counts" instead of X
# In this case, "Sample", 'pct_counts_mt', 'total_counts', 'pct_counts_ribo' are expected to contribute to the noises
scvi.model.SCVI.setup_anndata(
    processed_adata,
    # The primary batch info
    batch_key="sample",
    continuous_covariate_keys=["pct_counts_mt", "total_counts", "pct_counts_ribo"],
)
model = scvi.model.SCVI(processed_adata)
model.train(
    accelerator="gpu",
    batch_size=SINGLE_CELL_VAE_BATCH_SIZE,
    datasplitter_kwargs=DataLoader,
    train_size=0.9,
    check_val_every_n_epoch=1,
)
plot.plot_validation_loss(
    model, processed_adata.obs["series"].iloc[0] + "_integrated_validation_loss.svg"
)

# latent_representation: (cell, latent_space_dimension)
processed_adata.obsm["X_scvi"] = model.get_latent_representation()
del model
gc.collect()

processed_h5ad_location = find_env_dir("PROCESSED_H5AD_LOCATION")
processed_adata.write_h5ad(
    os.path.join(
        processed_h5ad_location, processed_adata.obs["series"].iloc[0] + ".h5ad"
    )
)

# %% Visualizes UMAP with leiden clusters and samples (Rendering a graph each)

# Uses pre-calculated SCVI latent representation for calculating similarity score and constructing neighborhood graph
# Store settings in .uns["neighbors"] and connectivity matrices in .obsp
sc.pp.neighbors(processed_adata, n_neighbors=10, use_rep="X_scvi")
# Embeds the neighborhood graph into 2D space using UMAP algorithm (optimized via SGD, Stochastic Gradient Descent)
# You can change n_components to 3 for 3D UMAP
sc.tl.umap(processed_adata, n_components=2, min_dist=0.15)

# If the clusters appear too clumped or merged, try decreasing n_neighbors and min_dist

# Clustering cells using leiden algorithm, maximizes modularity which is defined based on its intergroup connectivity and expected (random) connectivity
# High resolution value results in more clusters
sc.tl.leiden(
    processed_adata, resolution=1.0, flavor="igraph", n_iterations=-1, directed=False
)

clustered_data_location = find_env_dir("CLUSTERED_DATA_LOCATION")
processed_adata.write_h5ad(
    os.path.join(
        clustered_data_location,
        processed_adata.obs["series"].iloc[0] + "_clustered.h5ad",
    )
)

plot.plot_umap(processed_adata, has_celltype=True, highlight_cells=["Enteric_Glia"])
