# %% Environment Setup
import gc
import os
import numpy as np
import pandas as pd
import scanpy as sc
import scvi
from anndata import AnnData
from scipy.sparse import csr_matrix
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats
from pipeline.utils import plot
from pipeline.utils.env import find_env_dir
from pipeline.config.constants import (
    DOUBLET_REMOVAL_VAE_BATCH_SIZE,
    DOUBLET_REMOVAL_SOLO_BATCH_SIZE,
    SINGLE_CELL_VAE_BATCH_SIZE,
    CPU_CORE_COUNT,
)
from pipeline.config.machine_learning import DataLoader

# Loading .env
h5ad_count_matrix_location = find_env_dir("H5AD_COUNT_MATRIX_LOCATION")
file_name = "GSE232703_duodenum.h5ad"
file = os.path.join(h5ad_count_matrix_location, file_name)


# %%  Preprocessing functions
# Detecting and annotating doublets using SCVI and SOLO
def doublet_removal(adata: AnnData) -> AnnData:
    # Select genes which are expressed in at least 10 cells
    filtered_genes_candidate = sc.pp.filter_genes(adata, min_cells=10, inplace=False)
    if filtered_genes_candidate is None:
        raise ValueError("No gene left after filtering")
    filtered_genes, _ = filtered_genes_candidate

    # Select genes with high variance
    # VST (Variance Stabilizing Transformation) algorithm (in this case, seruat_v3) is applied due to high variance in genes with high level of expression
    # Variance Stabilization is needed to select genes with whose variance is higher than expected
    adata_gene_view = adata[:, filtered_genes]
    highly_variable_genes_candidate = sc.pp.highly_variable_genes(
        adata_gene_view,
        n_top_genes=2000,
        subset=False,
        flavor="seurat_v3",
        inplace=False,
    )
    if highly_variable_genes_candidate is None:
        raise ValueError("Failed to compute highly variable genes")
    highly_variable_genes = highly_variable_genes_candidate

    vae_adata = adata_gene_view[
        :, highly_variable_genes["highly_variable"].to_numpy()
    ].copy()

    # Single-Cell Variational Inference (SCVI) separates technical noise (batch effect, library size) from the data
    # By using ZINB (Zero-Inflated Negative Binominal) distribution, zero-inflation (too many zeros, because negative count is impossible) and overdispersion (dispersion greater than mean value, because certain RNAs exhibit minimal basal trnanscription but undergo rapid induction only under specific conditions) can be handled
    # SCVI uses VAE (Variational AutoEncoder) structure, encoder maps data x into latent varaible z and decoder restores data x from latent variable z and technical noises

    # Adds fields to the AnnData objet to make it ready for building a Pytorch neural network
    # By default every cell is considered as a single batch
    scvi.model.SCVI.setup_anndata(vae_adata)

    # Constructs a VAE Pytorch neural network, not yet trained (Weights are initialized with random values)
    # Default dimension of SCVI latent space is 10
    vae = scvi.model.SCVI(vae_adata, n_latent=10)
    # Trains a VAE Pytorch neural network
    vae.train(
        accelerator="gpu",
        batch_size=DOUBLET_REMOVAL_VAE_BATCH_SIZE,
        datasplitter_kwargs=DataLoader,
        train_size=0.9,
        check_val_every_n_epoch=1,
    )
    plot.plot_validation_loss(
        vae, vae_adata.obs["series"].iloc[0] + "_validation_loss.svg"
    )

    # SOLO (Single-cell Doublet Detection via Variational Inference) identifies whether the cell is a singlet or a doublet
    # A decoder of VAE is not required because technical noise has already been accounted for and filtered out with the latent representation produced by the encoder

    # Constructs a SOLO instance by attaching a classifier head to the pretrained VAE encoder
    solo = scvi.external.SOLO.from_scvi_model(vae)
    # SOLO utilizes Positive-Unlabeled (PU) learning, incorporating synthetic doublets generated by summing the counts of two randomly selected cells.
    # This could reveal both heterotypic doublets (e.g. T cell + B cell) and homotypic doublets (e.g. T cell + T cell)
    # Trains a SOLO instance
    solo.train(
        accelerator="gpu",
        batch_size=DOUBLET_REMOVAL_SOLO_BATCH_SIZE,
        datasplitter_kwargs=DataLoader,
        train_size=0.9,
        check_val_every_n_epoch=1,
    )
    plot.plot_validation_loss(
        solo, vae_adata.obs["series"].iloc[0] + "_solo_validation_loss.svg"
    )
    # 'soft' True returns probabilities for singlet and doublet
    solo_probs = solo.predict(soft=True)
    adata.obs["singlet_probability"] = solo_probs["singlet"]

    del vae, solo, vae_adata
    gc.collect()

    return adata


# Quality assessment by calculating QC metrics
def quality_assess(adata: AnnData, ribo_genes: pd.DataFrame) -> AnnData:
    # Marking mitochondrial and ribosomal genes
    mt_mask = adata.var.index.str.startswith("MT-")
    ribo_mask = adata.var_names.isin(ribo_genes[0].values)
    adata.var["mt"] = np.asarray(mt_mask, dtype=bool)
    adata.var["ribo"] = np.asarray(ribo_mask, dtype=bool)

    # Generates QC metrics
    # qc_vars: List of categories that you want to make as a QC metrics (It must be set as a boolean list in AnnData.obs)
    sc.pp.calculate_qc_metrics(
        adata, qc_vars=["mt", "ribo"], percent_top=[20], log1p=True, inplace=True
    )

    return adata


# %%
ribo_url = "http://software.broadinstitute.org/gsea/msigdb/download_geneset.jsp?geneSetName=KEGG_RIBOSOME&fileType=txt"
ribo_genes = pd.read_table(ribo_url, skiprows=2, header=None)

# Preprocessing each sample
print("Loading data...")
loaded_adata = sc.read_h5ad(file)

print("Removing doublets...")
doublet_removed_adata = doublet_removal(loaded_adata)

print("Assessing quality...")
quality_assessed_adata = quality_assess(doublet_removed_adata, ribo_genes)
# Cell and gene filtering
sc.pp.filter_cells(quality_assessed_adata, min_genes=200)
sc.pp.filter_genes(quality_assessed_adata, min_cells=10)
# Filtered cells and genes necessitate re-calculation of QC metrics
quality_assessed_adata = quality_assess(quality_assessed_adata, ribo_genes)

plot.plot_qc(quality_assessed_adata)
series_name = quality_assessed_adata.obs["series"].iloc[0]

# Cytoplasmic RNA in dead cells leaks out, resulting in a higher proportion of remaining mitochondrial RNA
quality_assessed_adata = quality_assessed_adata[
    (quality_assessed_adata.obs["pct_counts_mt"] < 15)
    & (quality_assessed_adata.obs["singlet_probability"] > 0.6)
].copy()

filtered_adata = quality_assessed_adata
gc.collect()

filtered_count_matrix_location = find_env_dir("FILTERED_COUNT_MATRIX_LOCATION")
filtered_adata.write_h5ad(
    os.path.join(filtered_count_matrix_location, series_name + ".h5ad")
)

# %% Producing latent representation of cells using scVI
print("Producing latent representation of cells using scVI...")
# Setting up AnnData for scVI model with batch effects
scvi.model.SCVI.setup_anndata(
    filtered_adata,
    # The primary batch info
    batch_key="batch",
)
model = scvi.model.SCVI(filtered_adata)
model.train(
    accelerator="gpu",
    batch_size=SINGLE_CELL_VAE_BATCH_SIZE,
    datasplitter_kwargs=DataLoader,
    train_size=0.9,
    check_val_every_n_epoch=1,
)
plot.plot_validation_loss(model, series_name + "_model_validation_loss.svg")

# latent_representation: (cell, latent_space_dimension)
filtered_adata.obsm["X_scvi"] = model.get_latent_representation()

scvi_model_location = find_env_dir("SCVI_MODEL_LOCATION")
model.save(
    os.path.join(scvi_model_location, series_name), overwrite=True, save_anndata=True
)

# %% Clustering and DE analysis
# Uses pre-calculated scVI latent representation for calculating similarity score and constructing neighborhood graph
# Store settings in .uns["neighbors"] and connectivity matrices in .obsp
print("Constructing neighborhood graph...")
sc.pp.neighbors(filtered_adata, n_neighbors=10, use_rep="X_scvi")
# Embeds the neighborhood graph into 2D space using UMAP algorithm (optimized via SGD, Stochastic Gradient Descent)
# You can change n_components to 3 for 3D UMAP
print("Calculating UMAP...")
sc.tl.umap(filtered_adata, n_components=2, min_dist=0.2)
# If the clusters appear too clumped or merged, try decreasing n_neighbors and min_dist

# Clustering cells using leiden algorithm, maximizes modularity which is defined based on its intergroup connectivity and expected (random) connectivity
# High resolution value results in more clusters
print("Clustering with Leiden algorithm...")
sc.tl.leiden(
    filtered_adata, resolution=1.0, flavor="igraph", n_iterations=-1, directed=False
)
plot.plot_umap(filtered_adata)

# Differential expression analysis is not performed on scVI denoised data because of imputation artifacts
# Instead, pseudobulk differential expression analysis using DESeq2 is performed
print("Differential expression analysis...")

clustered_data_location = find_env_dir("CLUSTERED_DATA_LOCATION")
de_analysis_location = find_env_dir("DE_ANALYSIS_LOCATION")

filtered_adata.write_h5ad(
    os.path.join(
        clustered_data_location,
        series_name + "_clustered.h5ad",
    )
)


def pseudobulk_deseq2(adata: AnnData, cluster_key="leiden"):
    clusters = adata.obs[cluster_key].unique().tolist()
    samples = adata.obs["sample"].unique().tolist()

    results = []
    for cluster in clusters:
        rows, meta, idx = [], [], []

        for sample in samples:
            mask_sample = adata.obs["sample"] == sample
            mask_sample_cluster = mask_sample & (adata.obs[cluster_key] == cluster)
            mask_sample_rest = mask_sample & (adata.obs[cluster_key] != cluster)

            n_cells_cluster = int(mask_sample_cluster.sum())
            n_cells_rest = int(mask_sample_rest.sum())

            if n_cells_cluster < 50 or n_cells_rest < 50:
                continue

            sample_cluster_adata = adata[mask_sample_cluster]
            assert isinstance(sample_cluster_adata.X, csr_matrix)
            rows.append(np.asarray(sample_cluster_adata.X.sum(axis=0)).ravel())
            meta.append(
                {
                    "sample": sample,
                    "group": "cluster",
                    "n_cells": n_cells_cluster,
                    "batch": sample,
                }
            )
            idx.append(f"{sample}_{cluster}")

            sample_rest_adata = adata[mask_sample_rest]
            assert isinstance(sample_rest_adata.X, csr_matrix)
            rows.append(np.asarray(sample_rest_adata.X.sum(axis=0)).ravel())
            meta.append(
                {
                    "sample": sample,
                    "group": "rest",
                    "n_cells": n_cells_rest,
                    "batch": sample,
                }
            )
            idx.append(f"{sample}_{cluster}_rest")

        if len(rows) < 4:
            print("Not enough samples for cluster ", cluster)
            continue
        counts = pd.DataFrame(rows, index=idx, columns=adata.var_names)
        meta = pd.DataFrame(meta, index=idx)
        print(counts)
        print(meta)

        dds = DeseqDataSet(
            counts=counts,
            metadata=meta,
            design="~batch + group",
            refit_cooks=True,
            n_cpus=CPU_CORE_COUNT,
        )
        sc.pp.filter_genes(dds, min_cells=1)
        dds.deseq2()

        ds = DeseqStats(
            dds, contrast=["group", "cluster", "rest"], n_cpus=CPU_CORE_COUNT
        )
        ds.summary()

        res = ds.results_df.copy()
        res["cluster"] = cluster
        res["contrast"] = "rest"
        res["cluster_key"] = cluster_key
        res = res.reset_index().rename(columns={"index": "gene"})

        results.append(res)

    results = pd.concat(results, axis=0, ignore_index=True)
    results.to_csv(os.path.join(de_analysis_location, series_name + "_deseq2.csv"))


pseudobulk_deseq2(filtered_adata)
